- name: Ensure pip3 is installed
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install boto3 and botocore
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
    executable: pip3

- name: create ec2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    component:  # Specify the component name here, e.g., webserver, database, etc.
      - mongodb
  roles:
    - ec2
  # tasks:
  # - name: Launch ec2 for each component
  #   include_role:
  #     name: ec2
  #   vars:
  #     components: "{{ item }}"
  #   loop: "{{ component }}"
    