- name: Setup environment and create EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    component:  # Specify the component name here, e.g., webserver, database, etc.
      - mongodb

  tasks:
    - name: Ensure pip3 is installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install boto3 and botocore
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
        executable: pip3
    - name: Include ec2 role
        ansible.builtin.include_role:
          name: ec2
    # tasks:
    # - name: Launch ec2 for each component
    #   include_role:
    #     name: ec2
    #   vars:
    #     components: "{{ item }}"
    #   loop: "{{ component }}"
      