- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: setup python packages
  include_role:
    name: common
    tasks_from: python

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd