- name: Create EC2 instance
  amazon.aws.ec2_instance:
    name: "{{ component }}"
    image_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    region: us-east-1
    security_groups: sg-0c02775e9220c1fde
    zone: augustys.fun
    tags:
    Name: "{{ item }}"
  loop:
    - "{{ component }}"
  register: ec2-output

- name: Show instance details
  ansible.builtin.debug:
  msg: "{{ ec2_output }}"

